export const IMAGES = {
  hero: "/hero/hero8.png",
  heroAlt: {
    primary: "/hero/hero1.png",
    sunset: "/hero/hero2.png",
    celebration: "/hero/hero3.png",
    couple: "/hero/hero4.png",
    invitation: "/hero/hero5.png",
    welcomeNote: "/hero/hero6.png",
    rsvp: "/hero/hero7.png",
    footer: "/hero/heroFooter.png",
    weddingWeekend: "/hero/weddingweekendHero.png",
    welcomeToKerala: "/hero/welcometoKerelaHero.png",
  },
  logo: {
    light: "/logo/lightlogo.png",
    dark: "/logo/darklogo.png",
    wedding: "/logo/weddinglogo.png",
    main: "/logo/mainLogo.png",
    paypal: "/logos/paypal.svg",
    revolut: "/logos/revolut.svg",
  },
  decor: {
    sandDollar: "/images/decor/line-art-sand-dollar.avif",
    resortPool: "/images/decor/resortpool.png",
    weekendHeader: "/images/decor/weekendimage.png",
    bananaLeaves: "/images/decor/banana-leaves-watercolor.png",
    bananaPlant: "/images/decor/banana-leaves-plant.png",
    bananaCorner: "/images/decor/bananacorner.png",
    bananaFlower: "/images/decor/banana-flower-botanical.png",
    eucalyptus: "/images/decor/eucalyptus-branch.avif",
    oliveBranch: "/images/decor/olive-branch.avif",
    bougainvillea: "/images/decor/pink-bougainvillea.png",
    hangingJasmine: "/images/decor/hanging-jasmine-bell.jpg",
    floralElephant: "/images/decor/floral-elephant-stands.png",
    lotusCluster: "/images/decor/pink-lotus-cluster.png",
    peonySingle: "/images/decor/white-peony-single.avif",
    peonyWithBud: "/images/decor/white-peony-with-bud.avif",
    peonyPair: "/images/decor/white-peony-pair.avif",
    houseboat: "/images/decor/kerala-backwaters-houseboat.png",
    coupleIllustration: "/images/decor/anshul&sarah.png",
    welcomeNoteIllustration: "/images/decor/welcomenote.png",
    travelAndStayHeader: "/images/decor/travel&StayHeader.png",
    rsvpHeader: "/images/decor/rsvpHeader.png",
  },
  couple: {
    primary: "/couple/anshulSarah1.jpeg",
    secondary: "/couple/anshulSarah2.jpeg",
  },
  venueKerala: {
    bridgeEntrance: "/venueKerela/SPN05856.jpg",
    poolHouseboats: "/venueKerela/SPN06787.jpg",
    backwatersLawn: "/venueKerela/SPN06795.jpg",
    timeline: "/venueKerela/timeline.png",
    kumarakomFull: "/venueKerela/SPN05873.jpg",
    sunsetPool: "/venueKerela/SPN09791.jpg",
    resortFacade: "/venueKerela/SPN05850.jpg",
    resortGardens: "/venueKerela/SPN05912.jpg",
    heritageLakeVillas: "/venueKerela/heritage-lake-view-villas-4.jpg",
    houseboats: "/venueKerela/houseboats-6.jpg",
    meanderingPoolVillas: "/venueKerela/meandering-pool-duplex-villas-3.jpg",
    vembanadSeafoodBar: "/venueKerela/vembanad-the-seafood-bar-2.jpg",
  },
  kerala: {
    spiritOfKerala: "/kerala/images/spiritofkerela.png",
    placesArt: "/kerala/images/kerelaPlacesArt.png",
    header: "/kerala/images/kerelaHeader.png",
    kumarakomArt: "/kerala/images/kumarakomArt.png",
    gettingHereArt: "/kerala/images/gettinghereArt.png",
    kochi: "/kerala/images/kochi.png",
    munnar: "/kerala/images/munnar.png",
    varkala: "/kerala/images/varkala.png",
    kovalam: "/kerala/images/kovalam.png",
  },
  patterns: {
    divider: "/patterns/divider.png",
    paperTexture: "/patterns/paperTexture.png",
    sealButton: "/patterns/sealbutton.png",
    weekendSeal: "/patterns/weekendSeal.png",
    rsvpSeal: "/patterns/rsvpSeal.png",
    ivorySeal: "/patterns/ivorySeal.png",
    bulletPoint: "/patterns/bulletpoint.png",
  },

  keralaBackwaters:
    "https://images.unsplash.com/photo-1587474260587-136574528ed5?w=1600&q=85",
  keralaTemple:
    "https://images.unsplash.com/photo-1593693397690-362cb1bccf97?w=1600&q=85",
  houseboat:
    "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=1600&q=85",
  cuisine:
    "https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=1600&q=85",
  ayurveda:
    "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=1600&q=85",
  sunset:
    "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1600&q=85",
} as const;
